name: 'Mountainology '
favicon: null
layout_spectrum: 0.022143519017845392
typography_spectrum: 0.8430097131058574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9496599300764501
  lightness: 0.32078767311759293
  saturation: 0.6133480360731483
  rhythmicContrast: 0.8444983551744372
purpose: []
